let Menudata = [
  {
    Image:
      "https://res.cloudinary.com/freshly/image/upload/c_scale,w_640/c_crop,h_341,w_512/v1637012873/production-meal-image-2fd3df62-8abf-413e-8650-afca039518ec.jpg",
    Title: "Steak Peppercorn",
    Nutritions: "500 Cal | Gluten Free | Single-Serve",
    price: "$ 29",
    catagory: "Significant",
    Mealcal: 500,
    mealcardsingle: "Single-Serve",
    mealcardmulti: "Multi-Serve",
    subrecipename: "with SautÃ©ed Carrots & French Green Beans",
    meallabel1: "Gluten Free",
    meallabel2: "Soy Free",
    meallabel3: "High Protein",
    modalimg:
      "https://assets-global.website-files.com/5d03b4e13011831ae4624b37/61ff6b82fa4a150d01cc5110_production-meal-image-6b3a83c1-9167-4a16-897e-d12f9460236a.jpeg",
    dishspecial1:
      "Tender, high-protein flat iron steak, grilled toÂ perfection",
    dishspecial2: "Bed of creamy mashed potatoes as a heartyÂ accompaniment",
    ingredientname1: "Green Beans",
    ingredientname2: "Flat Iron Steak",
    ingredientname2__1: "Red Potatoes",
    ingredientname3: "Carrots",
    ingredientname4: "Cassava Flour",
    ingredientname5: "Plain Yogurt",
  },
  {
    Image:
      "https://res.cloudinary.com/freshly/image/upload/c_scale,w_640/c_crop,h_341,w_512/v1659483513/production-meal-image-1d053d43-fedb-4c71-93e4-615f29442853.jpg",
    Title: "Hearty Veggie Bolognese",
    Nutritions: "490 Cal | Gluten Free | Single-Serve",
    price: "$ 20",
    catagory: "Significant",
    mealcardsingle: "Single-Serve",
    mealcardmulti: "Multi-Serve",
    subrecipename: "with Masterful Mac & Cheese",
    meallabel1: "High Protein",
    meallabel2: "Soy Free",
    meallabel3: "Gluten Free",
    modalimg:
      "https://assets-global.website-files.com/5d03b4e13011831ae4624b37/61ff6b8686c6705f190e7d43_production-meal-image-03fedc66-e34e-451c-a935-514e3602cbb2.jpeg",
    dishspecial1:
      "Greaseless oven-fried chicken breast, hand-breaded' with a gluten-free almond flourÂbatter",
    dishspecial2:
      "Our Masterful Mac is made with gluten-free brown-rice macaroni and a cheesy sauce thickened with butternutÂ squash",
    ingredientname1: "Butternut Squash",
    ingredientname2: "Cassava Flour",
    ingredientname2__1: "Elbow Macaroni",
    ingredientname3: "Green Beans",
    ingredientname4: "Chicken Breast",
    ingredientname5: "Almonds",
  },
  {
    Image:
      "https://res.cloudinary.com/freshly/image/upload/c_scale,w_640/c_crop,h_341,w_512/v1650468077/production-meal-image-aa45ad57-f3bd-41bf-b74b-7906066bdd24.jpg",
    Title: "Cuban Mojo Shrimp",
    Nutritions: "410 Cal | Gluten Free | Single-Serve",
    price: "$ 41",
    catagory: "FreshlyFit",
    mealcardsingle: "Single-Serve",
    mealcardmulti: "Multi-Serve",
    subrecipename: "with Masterful Mac & Cheese",
    meallabel1: "High Protein",
    meallabel2: "Soy Free",
    meallabel3: "Gluten Free",
    modalimg:
      "https://assets-global.website-files.com/5d03b4e13011831ae4624b37/61ff6b8686c6705f190e7d43_production-meal-image-03fedc66-e34e-451c-a935-514e3602cbb2.jpeg",
    dishspecial1:
      "Greaseless oven-fried chicken breast, hand-breaded' with a gluten-free almond flourÂbatter",
    dishspecial2:
      "Our Masterful Mac is made with gluten-free brown-rice macaroni and a cheesy sauce thickened with butternutÂ squash",
    ingredientname1: "Butternut Squash",
    ingredientname2: "Cassava Flour",
    ingredientname2__1: "Elbow Macaroni",
    ingredientname3: "Green Beans",
    ingredientname4: "Chicken Breast",
    ingredientname5: "Almonds",
  },
  {
    Image:
      "https://res.cloudinary.com/freshly/image/upload/c_scale,w_640/c_crop,h_341,w_512/v1637012265/production-meal-image-e4122aa8-0fe7-4854-b6f5-e27e0c5be918.jpg",
    Title: "Homestyle Chicken",
    Nutritions: "560 Cal | Gluten Free | Single-Serve",
    price: "$ 31",
    catagory: "Significant",
    Mealcal: 470,
    mealcardsingle: "Single-Serve",
    mealcardmulti: "Multi-Serve",
    subrecipename: "with SautÃ©ed Zucchini & Spinach",
    meallabel1: "Gluten Free",
    meallabel2: "Soy Free",
    meallabel3: "",
    modalimg:
      "https://assets-global.website-files.com/5d03b4e13011831ae4624b37/61ff6b8bdf3b65256cd159c7_production-meal-image-0963d196-5110-4dc7-888a-8121e5b91142.jpeg",
    dishspecial1:
      "Pasta night gets an upgrade with gluten-free brown-rice pasta and our Masterful Marinara, packed with 5 sneaky veggies and a touch ofÂ honey",
    dishspecial2: "Nitrate- and nitrite-free pork sausage with ItalianÂ spices",
    ingredientname1: "Italian Sausage",
    ingredientname2: "Spinach",
    ingredientname2__1: "Zucchini",
    ingredientname3: "Penne",
    ingredientname4: "Tomatoes",
    ingredientname5: "Marinara Sauce",
  },
  {
    Image:
      "https://res.cloudinary.com/freshly/image/upload/c_scale,w_640/c_crop,h_341,w_512/v1607770959/production-meal-image-7a62bb89-9bcb-4f1f-9f0f-d8372698d48e.jpg",
    Title: "Protein-Packed Chicken Parm",
    Nutritions: "410 Cal | Gluten Free | Single-Serve",
    price: "$ 21",
    catagory: "FreshlyFit",
    Mealcal: 560,
    mealcardsingle: "Single-Serve",
    mealcardmulti: "Multi-Serve",
    subrecipename: "with Masterful Mac & Cheese",
    meallabel1: "High Protein",
    meallabel2: "Soy Free",
    meallabel3: "Gluten Free",
    modalimg:
      "https://assets-global.website-files.com/5d03b4e13011831ae4624b37/61ff6b8686c6705f190e7d43_production-meal-image-03fedc66-e34e-451c-a935-514e3602cbb2.jpeg",
    dishspecial1:
      "Greaseless oven-fried chicken breast, hand-breaded' with a gluten-free almond flourÂbatter",
    dishspecial2:
      "Our Masterful Mac is made with gluten-free brown-rice macaroni and a cheesy sauce thickened with butternutÂ squash",
    ingredientname1: "Butternut Squash",
    ingredientname2: "Cassava Flour",
    ingredientname2__1: "Elbow Macaroni",
    ingredientname3: "Green Beans",
    ingredientname4: "Chicken Breast",
    ingredientname5: "Almonds",
  },
  {
    Image:
      "https://res.cloudinary.com/freshly/image/upload/c_scale,w_640/c_crop,h_341,w_512/v1637012554/production-meal-image-c9eef45a-97a9-487c-9550-71488e5f639a.jpg",
    Title: "Cauliflower Shell Beef Bolognese",
    Nutritions: "490 Cal | Gluten Free | Single-Serve",
    price: "$ 12",
    catagory: "Significant",
    Mealcal: 420,
    mealcardsingle: "Single-Serve",
    mealcardmulti: "Multi-Serve",
    subrecipename: "with Basmati Rice & Veggies",
    meallabel1: "<500 Cal",
    meallabel2: "Gluten Free",
    meallabel3: "Dairy Free",
    modalimg:
      "https://assets-global.website-files.com/5d03b4e13011831ae4624b37/61ff6b8e6dd23b334d122656_production-meal-image-9ad161f0-f33f-4551-b099-38188c9d783e.jpeg",
    dishspecial1:
      "In the Eastern US, this meal may include onions. Please check the ingredientÂ statement.",
    dishspecial2:
      "The salty-sweet flavors of chicken teriyaki just got a littleÂ better-for-you",
    ingredientname1: "Green Chickpeas",
    ingredientname2: "Teriyaki Sauce",
    ingredientname2__1: "Carrots",
    ingredientname3: "Coconut Nectar",
    ingredientname4: "Basmati Rice",
    ingredientname5: "Chicken Thigh",
  },
  {
    Image:
      "https://res.cloudinary.com/freshly/image/upload/c_scale,w_640/c_crop,h_341,w_512/v1637012391/production-meal-image-f0de55be-d691-4ade-bc26-b4a8aedaa1fe.jpg",
    Title: "Sausage Baked Penne",
    Nutritions: "470 Cal | Gluten Free | Single-Serve",
    price: "$ 40",
    catagory: "Significant",
    mealcardsingle: "Single-Serve",
    mealcardmulti: "Multi-Serve",
    subrecipename: "with SautÃ©ed Zucchini & Spinach",
    meallabel1: "Gluten Free",
    meallabel2: "Soy Free",
    meallabel3: "Dairy Free",
    modalimg:
      "https://assets-global.website-files.com/5d03b4e13011831ae4624b37/61ff6b8bdf3b65256cd159c7_production-meal-image-0963d196-5110-4dc7-888a-8121e5b91142.jpeg",
    dishspecial1:
      "Pasta night gets an upgrade with gluten-free brown-rice pasta and our Masterful Marinara, packed with 5 sneaky veggies and a touch ofÂ honey",
    dishspecial2: "Nitrate- and nitrite-free pork sausage with ItalianÂ spices",
    ingredientname1: "Italian Sausage",
    ingredientname2: "Spinach",
    ingredientname2__1: "Zucchini",
    ingredientname3: "Penne",
    ingredientname4: "Tomatoes",
    ingredientname5: "Marinara Sauce",
  },
  {
    Image:
      "https://res.cloudinary.com/freshly/image/upload/c_scale,w_640/c_crop,h_341,w_512/v1623678624/production-meal-image-86a5a9df-909d-4034-b6fa-6b48e5d110cf.jpg",
    Title: "Baked Turkey Meatballs & Zoodles",
    Nutritions: "360 Cal | Gluten Free | Single-Serve",
    price: "$ 35",
    catagory: "FreshlyFit",
    mealcardsingle: "Single-Serve",
    mealcardmulti: "Multi-Serve",
    subrecipename: "with SautÃ©ed Zucchini & Spinach",
    meallabel1: "Gluten Free",
    meallabel2: "Soy Free",
    meallabel3: "Dairy Free",
    modalimg:
      "https://assets-global.website-files.com/5d03b4e13011831ae4624b37/61ff6b8bdf3b65256cd159c7_production-meal-image-0963d196-5110-4dc7-888a-8121e5b91142.jpeg",
    dishspecial1:
      "Pasta night gets an upgrade with gluten-free brown-rice pasta and our Masterful Marinara, packed with 5 sneaky veggies and a touch ofÂ honey",
    dishspecial2: "Nitrate- and nitrite-free pork sausage with ItalianÂ spices",
    ingredientname1: "Italian Sausage",
    ingredientname2: "Spinach",
    ingredientname2__1: "Zucchini",
    ingredientname3: "Penne",
    ingredientname4: "Tomatoes",
    ingredientname5: "Marinara Sauce",
  },
  {
    Image:
      "https://res.cloudinary.com/freshly/image/upload/c_scale,w_640/c_crop,h_341,w_512/v1637012614/production-meal-image-92ec0fc1-d352-4720-9b83-96798ab8d2de.jpg",
    Title: "Savory-Sweet Chicken Teriyaki Bowl",
    Nutritions: "420 Cal | Gluten Free | Single-Serve",
    price: "$ 46",
    catagory: "Significant",
    mealcardsingle: "Single-Serve",
    mealcardmulti: "Multi-Serve",
    subrecipename: "with SautÃ©ed Zucchini & Spinach",
    meallabel1: "Gluten Free",
    meallabel2: "Soy Free",
    meallabel3: "Dairy Free",
    modalimg:
      "https://assets-global.website-files.com/5d03b4e13011831ae4624b37/61ff6b8bdf3b65256cd159c7_production-meal-image-0963d196-5110-4dc7-888a-8121e5b91142.jpeg",
    dishspecial1:
      "Pasta night gets an upgrade with gluten-free brown-rice pasta and our Masterful Marinara, packed with 5 sneaky veggies and a touch ofÂ honey",
    dishspecial2: "Nitrate- and nitrite-free pork sausage with ItalianÂ spices",
    ingredientname1: "Italian Sausage",
    ingredientname2: "Spinach",
    ingredientname2__1: "Zucchini",
    ingredientname3: "Penne",
    ingredientname4: "Tomatoes",
    ingredientname5: "Marinara Sauce",
  },
  {
    Image:
      "https://res.cloudinary.com/freshly/image/upload/c_scale,w_640/c_crop,h_341,w_512/v1637012331/production-meal-image-bc1b24c8-f62a-4756-a40e-173a8b67a590.jpg",
    Title: "Golden Oven-Fried Chicken & Mash",
    Nutritions: "510 Cal | Gluten Free | Single-Serve",
    price: "$ 26",
    catagory: "Significant",
    mealcardsingle: "Single-Serve",
    mealcardmulti: "Multi-Serve",
    subrecipename: "with SautÃ©ed Zucchini & Spinach",
    meallabel1: "Gluten Free",
    meallabel2: "Soy Free",
    meallabel3: "Dairy Free",
    modalimg:
      "https://assets-global.website-files.com/5d03b4e13011831ae4624b37/61ff6b8bdf3b65256cd159c7_production-meal-image-0963d196-5110-4dc7-888a-8121e5b91142.jpeg",
    dishspecial1:
      "Pasta night gets an upgrade with gluten-free brown-rice pasta and our Masterful Marinara, packed with 5 sneaky veggies and a touch ofÂ honey",
    dishspecial2: "Nitrate- and nitrite-free pork sausage with ItalianÂ spices",
    ingredientname1: "Italian Sausage",
    ingredientname2: "Spinach",
    ingredientname2__1: "Zucchini",
    ingredientname3: "Penne",
    ingredientname4: "Tomatoes",
    ingredientname5: "Marinara Sauce",
  },
  {
    Image:
      "https://res.cloudinary.com/freshly/image/upload/c_scale,w_640/c_crop,h_341,w_512/v1602259209/production-meal-image-4aa973ed-846f-4957-9341-272c1125725d.jpg",
    Title: "Very Verde Chicken",
    Nutritions: "470 Cal | Gluten Free | Single-Serve",
    price: "$ 28",
    catagory: "FreshlyFit",
    mealcardsingle: "Single-Serve",
    mealcardmulti: "Multi-Serve",
    subrecipename: "with SautÃ©ed Zucchini & Spinach",
    meallabel1: "Gluten Free",
    meallabel2: "Soy Free",
    meallabel3: "Dairy Free",
    modalimg:
      "https://assets-global.website-files.com/5d03b4e13011831ae4624b37/61ff6b8bdf3b65256cd159c7_production-meal-image-0963d196-5110-4dc7-888a-8121e5b91142.jpeg",
    dishspecial1:
      "Pasta night gets an upgrade with gluten-free brown-rice pasta and our Masterful Marinara, packed with 5 sneaky veggies and a touch ofÂ honey",
    dishspecial2: "Nitrate- and nitrite-free pork sausage with ItalianÂ spices",
    ingredientname1: "Italian Sausage",
    ingredientname2: "Spinach",
    ingredientname2__1: "Zucchini",
    ingredientname3: "Penne",
    ingredientname4: "Tomatoes",
    ingredientname5: "Marinara Sauce",
  },
  {
    Image:
      "https://res.cloudinary.com/freshly/image/upload/c_scale,w_640/c_crop,h_341,w_512/v1637012184/production-meal-image-ef64cbd3-cc91-4c5f-9865-b9ff0442572e.jpg",
    Title: "Zingy Buffalo Chicken",
    Nutritions: "470 Cal | Gluten Free | Single-Serve",
    price: "$ 21",
    catagory: "FreshlyFit",
    mealcardsingle: "Single-Serve",
    mealcardmulti: "Multi-Serve",
    subrecipename: "with SautÃ©ed Zucchini & Spinach",
    meallabel1: "Gluten Free",
    meallabel2: "Soy Free",
    meallabel3: "Dairy Free",
    modalimg:
      "https://assets-global.website-files.com/5d03b4e13011831ae4624b37/61ff6b8bdf3b65256cd159c7_production-meal-image-0963d196-5110-4dc7-888a-8121e5b91142.jpeg",
    dishspecial1:
      "Pasta night gets an upgrade with gluten-free brown-rice pasta and our Masterful Marinara, packed with 5 sneaky veggies and a touch ofÂ honey",
    dishspecial2: "Nitrate- and nitrite-free pork sausage with ItalianÂ spices",
    ingredientname1: "Italian Sausage",
    ingredientname2: "Spinach",
    ingredientname2__1: "Zucchini",
    ingredientname3: "Penne",
    ingredientname4: "Tomatoes",
    ingredientname5: "Marinara Sauce",
  },
  {
    Image:
      "https://res.cloudinary.com/freshly/image/upload/c_scale,w_640/c_crop,h_341,w_512/v1653506222/production-meal-image-8c822399-bb64-4643-9c22-9beba7f589dd.jpg",
    Title: "Grilled Lemon-Tahini Chicken",
    Nutritions: "380 Cal | Gluten Free | Single-Serve",
    price: "$ 14",
    catagory: "FreshlyFit",
    mealcardsingle: "Single-Serve",
    mealcardmulti: "Multi-Serve",
    subrecipename: "with SautÃ©ed Zucchini & Spinach",
    meallabel1: "Gluten Free",
    meallabel2: "Soy Free",
    meallabel3: "Dairy Free",
    modalimg:
      "https://assets-global.website-files.com/5d03b4e13011831ae4624b37/61ff6b8bdf3b65256cd159c7_production-meal-image-0963d196-5110-4dc7-888a-8121e5b91142.jpeg",
    dishspecial1:
      "Pasta night gets an upgrade with gluten-free brown-rice pasta and our Masterful Marinara, packed with 5 sneaky veggies and a touch ofÂ honey",
    dishspecial2: "Nitrate- and nitrite-free pork sausage with ItalianÂ spices",
    ingredientname1: "Italian Sausage",
    ingredientname2: "Spinach",
    ingredientname2__1: "Zucchini",
    ingredientname3: "Penne",
    ingredientname4: "Tomatoes",
    ingredientname5: "Marinara Sauce",
  },
  {
    Image:
      "https://res.cloudinary.com/freshly/image/upload/c_scale,w_640/c_crop,h_341,w_512/v1609775112/production-meal-image-17ade4a4-7351-4ff8-95c6-765d70e5ea5d.jpg",
    Title: "White Bean Turkey Chili Bowl",
    Nutritions: "510 Cal | Gluten Free | Single-Serve",
    price: "$ 16",
    catagory: "Significant",
    mealcardsingle: "Single-Serve",
    mealcardmulti: "Multi-Serve",
    subrecipename: "with SautÃ©ed Zucchini & Spinach",
    meallabel1: "Gluten Free",
    meallabel2: "Soy Free",
    meallabel3: "Dairy Free",
    modalimg:
      "https://assets-global.website-files.com/5d03b4e13011831ae4624b37/61ff6b8bdf3b65256cd159c7_production-meal-image-0963d196-5110-4dc7-888a-8121e5b91142.jpeg",
    dishspecial1:
      "Pasta night gets an upgrade with gluten-free brown-rice pasta and our Masterful Marinara, packed with 5 sneaky veggies and a touch ofÂ honey",
    dishspecial2: "Nitrate- and nitrite-free pork sausage with ItalianÂ spices",
    ingredientname1: "Italian Sausage",
    ingredientname2: "Spinach",
    ingredientname2__1: "Zucchini",
    ingredientname3: "Penne",
    ingredientname4: "Tomatoes",
    ingredientname5: "Marinara Sauce",
  },
  {
    Image:
      "https://res.cloudinary.com/freshly/image/upload/c_scale,w_640/c_crop,h_341,w_512/v1658322370/production-meal-image-5eb84c62-bb11-48e3-bb03-e19cd31b82d3.jpg",
    Title: "Oven-Baked Chicken Florentine",
    Nutritions: "410 Cal | Gluten Free | Single-Serve",
    price: "$ 34",
    catagory: "FreshlyFit",
    mealcardsingle: "Single-Serve",
    mealcardmulti: "Multi-Serve",
    subrecipename: "with SautÃ©ed Zucchini & Spinach",
    meallabel1: "Gluten Free",
    meallabel2: "Soy Free",
    meallabel3: "Dairy Free",
    modalimg:
      "https://assets-global.website-files.com/5d03b4e13011831ae4624b37/61ff6b8bdf3b65256cd159c7_production-meal-image-0963d196-5110-4dc7-888a-8121e5b91142.jpeg",
    dishspecial1:
      "Pasta night gets an upgrade with gluten-free brown-rice pasta and our Masterful Marinara, packed with 5 sneaky veggies and a touch ofÂ honey",
    dishspecial2: "Nitrate- and nitrite-free pork sausage with ItalianÂ spices",
    ingredientname1: "Italian Sausage",
    ingredientname2: "Spinach",
    ingredientname2__1: "Zucchini",
    ingredientname3: "Penne",
    ingredientname4: "Tomatoes",
    ingredientname5: "Marinara Sauce",
  },
  {
    Image:
      "https://res.cloudinary.com/freshly/image/upload/c_scale,w_640/c_crop,h_341,w_512/v1638803638/production-meal-image-a4feff11-ec91-43e8-bab5-e6daf8b55eea.jpg",
    Title: "Sesame-Ginger Chicken & Noodles",
    Nutritions: "430 Cal | Has Gluten | Single-Serve",
    price: "$ 23",
    catagory: "Significant",
    mealcardsingle: "Single-Serve",
    mealcardmulti: "Multi-Serve",
    subrecipename: "with SautÃ©ed Zucchini & Spinach",
    meallabel1: "Gluten Free",
    meallabel2: "Soy Free",
    meallabel3: "Dairy Free",
    modalimg:
      "https://assets-global.website-files.com/5d03b4e13011831ae4624b37/61ff6b8bdf3b65256cd159c7_production-meal-image-0963d196-5110-4dc7-888a-8121e5b91142.jpeg",
    dishspecial1:
      "Pasta night gets an upgrade with gluten-free brown-rice pasta and our Masterful Marinara, packed with 5 sneaky veggies and a touch ofÂ honey",
    dishspecial2: "Nitrate- and nitrite-free pork sausage with ItalianÂ spices",
    ingredientname1: "Italian Sausage",
    ingredientname2: "Spinach",
    ingredientname2__1: "Zucchini",
    ingredientname3: "Penne",
    ingredientname4: "Tomatoes",
    ingredientname5: "Marinara Sauce",
  },
  {
    Image:
      "https://res.cloudinary.com/freshly/image/upload/c_scale,w_640/c_crop,h_341,w_512/v1648059540/production-meal-image-43b9ce48-cbff-4c29-9ee8-58fc3974cdff.jpg",
    Title: "Oven-Glazed Chicken Marsala",
    Nutritions: "350 Cal | Gluten Free | Single-Serve",
    price: "$ 11",
    catagory: "FreshlyFit",
    mealcardsingle: "Single-Serve",
    mealcardmulti: "Multi-Serve",
    subrecipename: "with SautÃ©ed Zucchini & Spinach",
    meallabel1: "Gluten Free",
    meallabel2: "Soy Free",
    meallabel3: "Dairy Free",
    modalimg:
      "https://assets-global.website-files.com/5d03b4e13011831ae4624b37/61ff6b8bdf3b65256cd159c7_production-meal-image-0963d196-5110-4dc7-888a-8121e5b91142.jpeg",
    dishspecial1:
      "Pasta night gets an upgrade with gluten-free brown-rice pasta and our Masterful Marinara, packed with 5 sneaky veggies and a touch ofÂ honey",
    dishspecial2: "Nitrate- and nitrite-free pork sausage with ItalianÂ spices",
    ingredientname1: "Italian Sausage",
    ingredientname2: "Spinach",
    ingredientname2__1: "Zucchini",
    ingredientname3: "Penne",
    ingredientname4: "Tomatoes",
    ingredientname5: "Marinara Sauce",
  },
  {
    Image:
      "https://res.cloudinary.com/freshly/image/upload/c_scale,w_640/c_crop,h_341,w_512/v1637012800/production-meal-image-fa07e0dc-cb7f-43d7-a669-d35dc3fbcf93.jpg",
    Title: "Chicken Tikka Masala",
    Nutritions: "570 Cal | Gluten Free | Single-Serve",
    price: "$ 49",
    catagory: "Significant",
    mealcardsingle: "Single-Serve",
    mealcardmulti: "Multi-Serve",
    subrecipename: "with SautÃ©ed Zucchini & Spinach",
    meallabel1: "Gluten Free",
    meallabel2: "Soy Free",
    meallabel3: "Dairy Free",
    modalimg:
      "https://assets-global.website-files.com/5d03b4e13011831ae4624b37/61ff6b8bdf3b65256cd159c7_production-meal-image-0963d196-5110-4dc7-888a-8121e5b91142.jpeg",
    dishspecial1:
      "Pasta night gets an upgrade with gluten-free brown-rice pasta and our Masterful Marinara, packed with 5 sneaky veggies and a touch ofÂ honey",
    dishspecial2: "Nitrate- and nitrite-free pork sausage with ItalianÂ spices",
    ingredientname1: "Italian Sausage",
    ingredientname2: "Spinach",
    ingredientname2__1: "Zucchini",
    ingredientname3: "Penne",
    ingredientname4: "Tomatoes",
    ingredientname5: "Marinara Sauce",
  },
  {
    Image:
      "https://res.cloudinary.com/freshly/image/upload/c_scale,w_640/c_crop,h_341,w_512/v1656618906/production-meal-image-064ddd32-490c-4956-b5db-ded0b1e365d0.jpg",
    Title: "Chimichurri Rojo Seared Steak",
    Nutritions: "450 Cal | Gluten Free | Single-Serve",
    price: "$ 42",
    catagory: "FreshlyFit",
    mealcardsingle: "Single-Serve",
    mealcardmulti: "Multi-Serve",
    subrecipename: "with SautÃ©ed Zucchini & Spinach",
    meallabel1: "Gluten Free",
    meallabel2: "Soy Free",
    meallabel3: "Dairy Free",
    modalimg:
      "https://assets-global.website-files.com/5d03b4e13011831ae4624b37/61ff6b8bdf3b65256cd159c7_production-meal-image-0963d196-5110-4dc7-888a-8121e5b91142.jpeg",
    dishspecial1:
      "Pasta night gets an upgrade with gluten-free brown-rice pasta and our Masterful Marinara, packed with 5 sneaky veggies and a touch ofÂ honey",
    dishspecial2: "Nitrate- and nitrite-free pork sausage with ItalianÂ spices",
    ingredientname1: "Italian Sausage",
    ingredientname2: "Spinach",
    ingredientname2__1: "Zucchini",
    ingredientname3: "Penne",
    ingredientname4: "Tomatoes",
    ingredientname5: "Marinara Sauce",
  },
  {
    Image:
      "https://res.cloudinary.com/freshly/image/upload/c_scale,w_640/c_crop,h_341,w_512/v1626457027/production-meal-image-536ab066-5461-4cc0-bbad-f3246a0bb7df.jpg",
    Title: "3 Grilled Chicken Breasts (9.75 oz)",
    Nutritions: "160 Cal | Gluten Free | Multi-Serve",
    price: "$ 44",
    catagory: "protiens",
    mealcardsingle: "Single-Serve",
    mealcardmulti: "Multi-Serve",
    subrecipename: "with SautÃ©ed Zucchini & Spinach",
    meallabel1: "Gluten Free",
    meallabel2: "Soy Free",
    meallabel3: "Dairy Free",
    modalimg:
      "https://assets-global.website-files.com/5d03b4e13011831ae4624b37/61ff6b8bdf3b65256cd159c7_production-meal-image-0963d196-5110-4dc7-888a-8121e5b91142.jpeg",
    dishspecial1:
      "Pasta night gets an upgrade with gluten-free brown-rice pasta and our Masterful Marinara, packed with 5 sneaky veggies and a touch ofÂ honey",
    dishspecial2: "Nitrate- and nitrite-free pork sausage with ItalianÂ spices",
    ingredientname1: "Italian Sausage",
    ingredientname2: "Spinach",
    ingredientname2__1: "Zucchini",
    ingredientname3: "Penne",
    ingredientname4: "Tomatoes",
    ingredientname5: "Marinara Sauce",
  },
  {
    Image:
      "https://res.cloudinary.com/freshly/image/upload/c_scale,w_640/c_crop,h_341,w_512/v1656612702/production-meal-image-d30dad76-4b61-40ab-bdfc-0d7a907829a6.jpg",
    Title: "Roasted Tomato & Parmesan Risotto",
    Nutritions: "490 Cal | Gluten Free | Single-Serve",
    price: "$ 24",
    mealcardsingle: "Single-Serve",
    mealcardmulti: "Multi-Serve",
    subrecipename: "with SautÃ©ed Zucchini & Spinach",
    meallabel1: "Gluten Free",
    meallabel2: "Soy Free",
    meallabel3: "Dairy Free",
    modalimg:
      "https://assets-global.website-files.com/5d03b4e13011831ae4624b37/61ff6b8bdf3b65256cd159c7_production-meal-image-0963d196-5110-4dc7-888a-8121e5b91142.jpeg",
    dishspecial1:
      "Pasta night gets an upgrade with gluten-free brown-rice pasta and our Masterful Marinara, packed with 5 sneaky veggies and a touch ofÂ honey",
    dishspecial2: "Nitrate- and nitrite-free pork sausage with ItalianÂ spices",
    ingredientname1: "Italian Sausage",
    ingredientname2: "Spinach",
    ingredientname2__1: "Zucchini",
    ingredientname3: "Penne",
    ingredientname4: "Tomatoes",
    ingredientname5: "Marinara Sauce",
  },
  {
    Image:
      "https://res.cloudinary.com/freshly/image/upload/c_scale,w_640/c_crop,h_341,w_512/v1626451152/production-meal-image-578506ac-e956-4c6f-bcbc-4e709ab34f98.jpg",
    Title: "8 Baked Turkey Meatballs (9.98 oz)",
    Nutritions: "110 Cal | Gluten Free | Multi-Serve",
    price: "$ 13",
    catagory: "protiens",
    mealcardsingle: "Single-Serve",
    mealcardmulti: "Multi-Serve",
    subrecipename: "with SautÃ©ed Zucchini & Spinach",
    meallabel1: "Gluten Free",
    meallabel2: "Soy Free",
    meallabel3: "Dairy Free",
    modalimg:
      "https://assets-global.website-files.com/5d03b4e13011831ae4624b37/61ff6b8bdf3b65256cd159c7_production-meal-image-0963d196-5110-4dc7-888a-8121e5b91142.jpeg",
    dishspecial1:
      "Pasta night gets an upgrade with gluten-free brown-rice pasta and our Masterful Marinara, packed with 5 sneaky veggies and a touch ofÂ honey",
    dishspecial2: "Nitrate- and nitrite-free pork sausage with ItalianÂ spices",
    ingredientname1: "Italian Sausage",
    ingredientname2: "Spinach",
    ingredientname2__1: "Zucchini",
    ingredientname3: "Penne",
    ingredientname4: "Tomatoes",
    ingredientname5: "Marinara Sauce",
  },
  {
    Image:
      "https://res.cloudinary.com/freshly/image/upload/c_scale,w_640/c_crop,h_341,w_512/v1638803151/production-meal-image-63479068-f450-4424-a206-229bd42ab321.jpg",
    Title: "Asian-Style Chicken & Noodles",
    Nutritions: "400 Cal | Has Gluten | Single-Serve",
    price: "$ 37",
    catagory: "purelyplanet",
    mealcardsingle: "Single-Serve",
    mealcardmulti: "Multi-Serve",
    subrecipename: "with SautÃ©ed Zucchini & Spinach",
    meallabel1: "Gluten Free",
    meallabel2: "Soy Free",
    meallabel3: "Dairy Free",
    modalimg:
      "https://assets-global.website-files.com/5d03b4e13011831ae4624b37/61ff6b8bdf3b65256cd159c7_production-meal-image-0963d196-5110-4dc7-888a-8121e5b91142.jpeg",
    dishspecial1:
      "Pasta night gets an upgrade with gluten-free brown-rice pasta and our Masterful Marinara, packed with 5 sneaky veggies and a touch ofÂ honey",
    dishspecial2: "Nitrate- and nitrite-free pork sausage with ItalianÂ spices",
    ingredientname1: "Italian Sausage",
    ingredientname2: "Spinach",
    ingredientname2__1: "Zucchini",
    ingredientname3: "Penne",
    ingredientname4: "Tomatoes",
    ingredientname5: "Marinara Sauce",
  },
  {
    Image:
      "https://res.cloudinary.com/freshly/image/upload/c_scale,w_640/c_crop,h_341,w_512/v1658926478/production-meal-image-29e2b6e1-12af-405d-8b33-91e19b2a0fef.jpg",
    Title: "Tricolor Beef Lasagna",
    Nutritions: "640 Cal | Gluten Free | Single-Serve",
    price: "$ 39",
    catagory: "purelyplanet",
    mealcardsingle: "Single-Serve",
    mealcardmulti: "Multi-Serve",
    subrecipename: "with SautÃ©ed Zucchini & Spinach",
    meallabel1: "Gluten Free",
    meallabel2: "Soy Free",
    meallabel3: "Dairy Free",
    modalimg:
      "https://assets-global.website-files.com/5d03b4e13011831ae4624b37/61ff6b8bdf3b65256cd159c7_production-meal-image-0963d196-5110-4dc7-888a-8121e5b91142.jpeg",
    dishspecial1:
      "Pasta night gets an upgrade with gluten-free brown-rice pasta and our Masterful Marinara, packed with 5 sneaky veggies and a touch ofÂ honey",
    dishspecial2: "Nitrate- and nitrite-free pork sausage with ItalianÂ spices",
    ingredientname1: "Italian Sausage",
    ingredientname2: "Spinach",
    ingredientname2__1: "Zucchini",
    ingredientname3: "Penne",
    ingredientname4: "Tomatoes",
    ingredientname5: "Marinara Sauce",
  },
  {
    Image:
      "https://res.cloudinary.com/freshly/image/upload/c_scale,w_640/c_crop,h_341,w_512/v1649950529/production-meal-image-61221a9e-23cf-4042-a8ff-c15cc1493807.jpg",
    Title: "Creamy Marinara Lentil Pasta",
    Nutritions: "520 Cal | Gluten Free | Single-Serve",
    price: "$ 19",
    catagory: "purelyplanet",
    mealcardsingle: "Single-Serve",
    mealcardmulti: "Multi-Serve",
    subrecipename: "with SautÃ©ed Zucchini & Spinach",
    meallabel1: "Gluten Free",
    meallabel2: "Soy Free",
    meallabel3: "Dairy Free",
    modalimg:
      "https://assets-global.website-files.com/5d03b4e13011831ae4624b37/61ff6b8bdf3b65256cd159c7_production-meal-image-0963d196-5110-4dc7-888a-8121e5b91142.jpeg",
    dishspecial1:
      "Pasta night gets an upgrade with gluten-free brown-rice pasta and our Masterful Marinara, packed with 5 sneaky veggies and a touch ofÂ honey",
    dishspecial2: "Nitrate- and nitrite-free pork sausage with ItalianÂ spices",
    ingredientname1: "Italian Sausage",
    ingredientname2: "Spinach",
    ingredientname2__1: "Zucchini",
    ingredientname3: "Penne",
    ingredientname4: "Tomatoes",
    ingredientname5: "Marinara Sauce",
  },
  {
    Image:
      "https://res.cloudinary.com/freshly/image/upload/c_scale,w_640/c_crop,h_341,w_512/v1649953867/production-meal-image-c87d5ef6-072c-4e75-a8e1-fef772ef1b13.jpg",
    Title: "Romesco Grilled Chicken",
    Nutritions: "550 Cal | Gluten Free | Single-Serve",
    price: "$ 24",
    catagory: "FreshlyFit",
    mealcardsingle: "Single-Serve",
    mealcardmulti: "Multi-Serve",
    subrecipename: "with SautÃ©ed Zucchini & Spinach",
    meallabel1: "Gluten Free",
    meallabel2: "Soy Free",
    meallabel3: "Dairy Free",
    modalimg:
      "https://assets-global.website-files.com/5d03b4e13011831ae4624b37/61ff6b8bdf3b65256cd159c7_production-meal-image-0963d196-5110-4dc7-888a-8121e5b91142.jpeg",
    dishspecial1:
      "Pasta night gets an upgrade with gluten-free brown-rice pasta and our Masterful Marinara, packed with 5 sneaky veggies and a touch ofÂ honey",
    dishspecial2: "Nitrate- and nitrite-free pork sausage with ItalianÂ spices",
    ingredientname1: "Italian Sausage",
    ingredientname2: "Spinach",
    ingredientname2__1: "Zucchini",
    ingredientname3: "Penne",
    ingredientname4: "Tomatoes",
    ingredientname5: "Marinara Sauce",
  },
  {
    Image:
      "https://res.cloudinary.com/freshly/image/upload/c_scale,w_640/c_crop,h_341,w_512/v1637002787/production-meal-image-b70b17ff-88b4-453d-b192-2be3cc18e849.jpg",
    Title: "Dijon Pork Chop",
    Nutritions: "630 Cal | Gluten Free | Single-Serve",
    price: "$ 11",
    mealcardsingle: "Single-Serve",
    mealcardmulti: "Multi-Serve",
    subrecipename: "with SautÃ©ed Zucchini & Spinach",
    meallabel1: "Gluten Free",
    meallabel2: "Soy Free",
    meallabel3: "Dairy Free",
    modalimg:
      "https://assets-global.website-files.com/5d03b4e13011831ae4624b37/61ff6b8bdf3b65256cd159c7_production-meal-image-0963d196-5110-4dc7-888a-8121e5b91142.jpeg",
    dishspecial1:
      "Pasta night gets an upgrade with gluten-free brown-rice pasta and our Masterful Marinara, packed with 5 sneaky veggies and a touch ofÂ honey",
    dishspecial2: "Nitrate- and nitrite-free pork sausage with ItalianÂ spices",
    ingredientname1: "Italian Sausage",
    ingredientname2: "Spinach",
    ingredientname2__1: "Zucchini",
    ingredientname3: "Penne",
    ingredientname4: "Tomatoes",
    ingredientname5: "Marinara Sauce",
  },
  {
    Image:
      "https://res.cloudinary.com/freshly/image/upload/c_scale,w_640/c_crop,h_341,w_512/v1655959643/production-meal-image-857e178e-6526-43e2-a8f3-7b8eb178c3c1.jpg",
    Title: "Veggie-Loaded Burrito Bake",
    Nutritions: "650 Cal | Gluten Free | Single-Serve",
    price: "$ 30",
    catagory: "purelyplanet",
    mealcardsingle: "Single-Serve",
    mealcardmulti: "Multi-Serve",
    subrecipename: "with SautÃ©ed Zucchini & Spinach",
    meallabel1: "Gluten Free",
    meallabel2: "Soy Free",
    meallabel3: "Dairy Free",
    modalimg:
      "https://assets-global.website-files.com/5d03b4e13011831ae4624b37/61ff6b8bdf3b65256cd159c7_production-meal-image-0963d196-5110-4dc7-888a-8121e5b91142.jpeg",
    dishspecial1:
      "Pasta night gets an upgrade with gluten-free brown-rice pasta and our Masterful Marinara, packed with 5 sneaky veggies and a touch ofÂ honey",
    dishspecial2: "Nitrate- and nitrite-free pork sausage with ItalianÂ spices",
    ingredientname1: "Italian Sausage",
    ingredientname2: "Spinach",
    ingredientname2__1: "Zucchini",
    ingredientname3: "Penne",
    ingredientname4: "Tomatoes",
    ingredientname5: "Marinara Sauce",
  },
  {
    Image:
      "https://res.cloudinary.com/freshly/image/upload/c_scale,w_640/c_crop,h_341,w_512/v1612385113/production-meal-image-4663a574-d74a-4854-a881-ef4da5b24cee.jpg",
    Title: "Swede-ish Meatballs",
    Nutritions: "630 Cal | Gluten Free | Single-Serve",
    price: "$ 26",
    catagory: "Significant",
    mealcardsingle: "Single-Serve",
    mealcardmulti: "Multi-Serve",
    subrecipename: "with SautÃ©ed Zucchini & Spinach",
    meallabel1: "Gluten Free",
    meallabel2: "Soy Free",
    meallabel3: "Dairy Free",
    modalimg:
      "https://assets-global.website-files.com/5d03b4e13011831ae4624b37/61ff6b8bdf3b65256cd159c7_production-meal-image-0963d196-5110-4dc7-888a-8121e5b91142.jpeg",
    dishspecial1:
      "Pasta night gets an upgrade with gluten-free brown-rice pasta and our Masterful Marinara, packed with 5 sneaky veggies and a touch ofÂ honey",
    dishspecial2: "Nitrate- and nitrite-free pork sausage with ItalianÂ spices",
    ingredientname1: "Italian Sausage",
    ingredientname2: "Spinach",
    ingredientname2__1: "Zucchini",
    ingredientname3: "Penne",
    ingredientname4: "Tomatoes",
    ingredientname5: "Marinara Sauce",
  },
  {
    Image:
      "https://res.cloudinary.com/freshly/image/upload/c_scale,w_640/c_crop,h_341,w_512/v1645195663/production-meal-image-25f9ce2d-ca21-499e-a140-8d59b4733ec2.jpg",
    Title: "Flame-Seared Top Blade Steak",
    Nutritions: "610 Cal | Gluten Free | Single-Serve",
    price: "$ 46",
    catagory: "Significant",
    mealcardsingle: "Single-Serve",
    mealcardmulti: "Multi-Serve",
    subrecipename: "with SautÃ©ed Zucchini & Spinach",
    meallabel1: "Gluten Free",
    meallabel2: "Soy Free",
    meallabel3: "Dairy Free",
    modalimg:
      "https://assets-global.website-files.com/5d03b4e13011831ae4624b37/61ff6b8bdf3b65256cd159c7_production-meal-image-0963d196-5110-4dc7-888a-8121e5b91142.jpeg",
    dishspecial1:
      "Pasta night gets an upgrade with gluten-free brown-rice pasta and our Masterful Marinara, packed with 5 sneaky veggies and a touch ofÂ honey",
    dishspecial2: "Nitrate- and nitrite-free pork sausage with ItalianÂ spices",
    ingredientname1: "Italian Sausage",
    ingredientname2: "Spinach",
    ingredientname2__1: "Zucchini",
    ingredientname3: "Penne",
    ingredientname4: "Tomatoes",
    ingredientname5: "Marinara Sauce",
  },
  {
    Image:
      "https://res.cloudinary.com/freshly/image/upload/c_scale,w_640/c_crop,h_341,w_512/v1643385949/production-meal-image-0287e25c-7e2a-47fd-acef-ebaff360e858.jpg",
    Title: "Bistro French Onion Chicken",
    Nutritions: "630 Cal | Gluten Free | Single-Serve",
    price: "$ 20",
    catagory: "Significant",
    mealcardsingle: "Single-Serve",
    mealcardmulti: "Multi-Serve",
    subrecipename: "with SautÃ©ed Zucchini & Spinach",
    meallabel1: "Gluten Free",
    meallabel2: "Soy Free",
    meallabel3: "Dairy Free",
    modalimg:
      "https://assets-global.website-files.com/5d03b4e13011831ae4624b37/61ff6b8bdf3b65256cd159c7_production-meal-image-0963d196-5110-4dc7-888a-8121e5b91142.jpeg",
    dishspecial1:
      "Pasta night gets an upgrade with gluten-free brown-rice pasta and our Masterful Marinara, packed with 5 sneaky veggies and a touch ofÂ honey",
    dishspecial2: "Nitrate- and nitrite-free pork sausage with ItalianÂ spices",
    ingredientname1: "Italian Sausage",
    ingredientname2: "Spinach",
    ingredientname2__1: "Zucchini",
    ingredientname3: "Penne",
    ingredientname4: "Tomatoes",
    ingredientname5: "Marinara Sauce",
  },
  {
    Image:
      "https://res.cloudinary.com/freshly/image/upload/c_scale,w_640/c_crop,h_341,w_512/v1633017856/production-meal-image-8f27cccd-b0db-405a-9341-3f4adabcbe9c.jpg",
    Title: "Chicken Cordon Bleu",
    Nutritions: "710 Cal | Gluten Free | Single-Serve",
    price: "$ 38",
    catagory: "Significant",
    mealcardsingle: "Single-Serve",
    mealcardmulti: "Multi-Serve",
    subrecipename: "with SautÃ©ed Zucchini & Spinach",
    meallabel1: "Gluten Free",
    meallabel2: "Soy Free",
    meallabel3: "Dairy Free",
    modalimg:
      "https://assets-global.website-files.com/5d03b4e13011831ae4624b37/61ff6b8bdf3b65256cd159c7_production-meal-image-0963d196-5110-4dc7-888a-8121e5b91142.jpeg",
    dishspecial1:
      "Pasta night gets an upgrade with gluten-free brown-rice pasta and our Masterful Marinara, packed with 5 sneaky veggies and a touch ofÂ honey",
    dishspecial2: "Nitrate- and nitrite-free pork sausage with ItalianÂ spices",
    ingredientname1: "Italian Sausage",
    ingredientname2: "Spinach",
    ingredientname2__1: "Zucchini",
    ingredientname3: "Penne",
    ingredientname4: "Tomatoes",
    ingredientname5: "Marinara Sauce",
  },
  {
    Image:
      "https://res.cloudinary.com/freshly/image/upload/c_scale,w_640/c_crop,h_341,w_512/v1654103998/production-meal-image-7c022f67-5d91-4212-99a3-799b0049b49d.jpg",
    Title: "Pork Chile Colorado",
    Nutritions: "570 Cal | Gluten Free | Single-Serve",
    price: "$ 48",
    catagory: "Significant",
    mealcardsingle: "Single-Serve",
    mealcardmulti: "Multi-Serve",
    subrecipename: "with SautÃ©ed Zucchini & Spinach",
    meallabel1: "Gluten Free",
    meallabel2: "Soy Free",
    meallabel3: "Dairy Free",
    modalimg:
      "https://assets-global.website-files.com/5d03b4e13011831ae4624b37/61ff6b8bdf3b65256cd159c7_production-meal-image-0963d196-5110-4dc7-888a-8121e5b91142.jpeg",
    dishspecial1:
      "Pasta night gets an upgrade with gluten-free brown-rice pasta and our Masterful Marinara, packed with 5 sneaky veggies and a touch ofÂ honey",
    dishspecial2: "Nitrate- and nitrite-free pork sausage with ItalianÂ spices",
    ingredientname1: "Italian Sausage",
    ingredientname2: "Spinach",
    ingredientname2__1: "Zucchini",
    ingredientname3: "Penne",
    ingredientname4: "Tomatoes",
    ingredientname5: "Marinara Sauce",
  },
  {
    Image:
      "https://res.cloudinary.com/freshly/image/upload/c_scale,w_640/c_crop,h_341,w_512/v1654626485/production-meal-image-eea55b43-0737-4923-912f-d2aa340a7bc0.jpg",
    Title: "Thai Green Curry Bowl",
    Nutritions: "390 Cal | Gluten Free | Single-Serve",
    price: "$ 14",
    catagory: "purelyplanet",
    mealcardsingle: "Single-Serve",
    mealcardmulti: "Multi-Serve",
    subrecipename: "with SautÃ©ed Zucchini & Spinach",
    meallabel1: "Gluten Free",
    meallabel2: "Soy Free",
    meallabel3: "Dairy Free",
    modalimg:
      "https://assets-global.website-files.com/5d03b4e13011831ae4624b37/61ff6b8bdf3b65256cd159c7_production-meal-image-0963d196-5110-4dc7-888a-8121e5b91142.jpeg",
    dishspecial1:
      "Pasta night gets an upgrade with gluten-free brown-rice pasta and our Masterful Marinara, packed with 5 sneaky veggies and a touch ofÂ honey",
    dishspecial2: "Nitrate- and nitrite-free pork sausage with ItalianÂ spices",
    ingredientname1: "Italian Sausage",
    ingredientname2: "Spinach",
    ingredientname2__1: "Zucchini",
    ingredientname3: "Penne",
    ingredientname4: "Tomatoes",
    ingredientname5: "Marinara Sauce",
  },
  {
    Image:
      "https://res.cloudinary.com/freshly/image/upload/c_scale,w_640/c_crop,h_341,w_512/v1651068673/production-meal-image-74a2ccd1-00a7-40df-b3cf-df2e105b657d.jpg",
    Title: "Tex-Mex Grilled Chicken",
    Nutritions: "550 Cal | Gluten Free | Single-Serve",
    price: "$ 23",
    catagory: "Significant",
    mealcardsingle: "Single-Serve",
    mealcardmulti: "Multi-Serve",
    subrecipename: "with SautÃ©ed Zucchini & Spinach",
    meallabel1: "Gluten Free",
    meallabel2: "Soy Free",
    meallabel3: "Dairy Free",
    modalimg:
      "https://assets-global.website-files.com/5d03b4e13011831ae4624b37/61ff6b8bdf3b65256cd159c7_production-meal-image-0963d196-5110-4dc7-888a-8121e5b91142.jpeg",
    dishspecial1:
      "Pasta night gets an upgrade with gluten-free brown-rice pasta and our Masterful Marinara, packed with 5 sneaky veggies and a touch ofÂ honey",
    dishspecial2: "Nitrate- and nitrite-free pork sausage with ItalianÂ spices",
    ingredientname1: "Italian Sausage",
    ingredientname2: "Spinach",
    ingredientname2__1: "Zucchini",
    ingredientname3: "Penne",
    ingredientname4: "Tomatoes",
    ingredientname5: "Marinara Sauce",
  },
  {
    Image:
      "https://res.cloudinary.com/freshly/image/upload/c_scale,w_640/c_crop,h_341,w_512/v1655312261/production-meal-image-48af6169-a821-442b-ae63-e7ec7983864a.jpg",
    Title: "Asian-Inspired Vegetable Stir-Fry",
    Nutritions: "480 Cal | Gluten Free | Single-Serve",
    price: "$ 50",
    catagory: "purelyplanet",
    mealcardsingle: "Single-Serve",
    mealcardmulti: "Multi-Serve",
    subrecipename: "with SautÃ©ed Zucchini & Spinach",
    meallabel1: "Gluten Free",
    meallabel2: "Soy Free",
    meallabel3: "Dairy Free",
    modalimg:
      "https://assets-global.website-files.com/5d03b4e13011831ae4624b37/61ff6b8bdf3b65256cd159c7_production-meal-image-0963d196-5110-4dc7-888a-8121e5b91142.jpeg",
    dishspecial1:
      "Pasta night gets an upgrade with gluten-free brown-rice pasta and our Masterful Marinara, packed with 5 sneaky veggies and a touch ofÂ honey",
    dishspecial2: "Nitrate- and nitrite-free pork sausage with ItalianÂ spices",
    ingredientname1: "Italian Sausage",
    ingredientname2: "Spinach",
    ingredientname2__1: "Zucchini",
    ingredientname3: "Penne",
    ingredientname4: "Tomatoes",
    ingredientname5: "Marinara Sauce",
  },
  {
    Image:
      "https://res.cloudinary.com/freshly/image/upload/c_scale,w_640/c_crop,h_341,w_512/v1639417068/production-meal-image-9e969581-d09c-4617-9b17-d455d23c8952.jpg",
    Title: "BBQ Bison Burger*",
    Nutritions: "610 Cal | Gluten Free | Single-Serve",
    price: "$ 21",
    catagory: "Significant",
    mealcardsingle: "Single-Serve",
    mealcardmulti: "Multi-Serve",
    subrecipename: "with SautÃ©ed Zucchini & Spinach",
    meallabel1: "Gluten Free",
    meallabel2: "Soy Free",
    meallabel3: "Dairy Free",
    modalimg:
      "https://assets-global.website-files.com/5d03b4e13011831ae4624b37/61ff6b8bdf3b65256cd159c7_production-meal-image-0963d196-5110-4dc7-888a-8121e5b91142.jpeg",
    dishspecial1:
      "Pasta night gets an upgrade with gluten-free brown-rice pasta and our Masterful Marinara, packed with 5 sneaky veggies and a touch ofÂ honey",
    dishspecial2: "Nitrate- and nitrite-free pork sausage with ItalianÂ spices",
    ingredientname1: "Italian Sausage",
    ingredientname2: "Spinach",
    ingredientname2__1: "Zucchini",
    ingredientname3: "Penne",
    ingredientname4: "Tomatoes",
    ingredientname5: "Marinara Sauce",
  },
  {
    Image:
      "https://res.cloudinary.com/freshly/image/upload/c_scale,w_640/c_crop,h_341,w_512/v1652892314/production-meal-image-4e60254a-6b6e-461b-9ec7-a25a2035949f.jpg",
    Title: "Creamy Chicken Fettuccine Alfredo",
    Nutritions: "360 Cal | Has Gluten | Single-Serve",
    price: "$ 12",
    catagory: "Significant",
    mealcardsingle: "Single-Serve",
    mealcardmulti: "Multi-Serve",
    subrecipename: "with SautÃ©ed Zucchini & Spinach",
    meallabel1: "Gluten Free",
    meallabel2: "Soy Free",
    meallabel3: "Dairy Free",
    modalimg:
      "https://assets-global.website-files.com/5d03b4e13011831ae4624b37/61ff6b8bdf3b65256cd159c7_production-meal-image-0963d196-5110-4dc7-888a-8121e5b91142.jpeg",
    dishspecial1:
      "Pasta night gets an upgrade with gluten-free brown-rice pasta and our Masterful Marinara, packed with 5 sneaky veggies and a touch ofÂ honey",
    dishspecial2: "Nitrate- and nitrite-free pork sausage with ItalianÂ spices",
    ingredientname1: "Italian Sausage",
    ingredientname2: "Spinach",
    ingredientname2__1: "Zucchini",
    ingredientname3: "Penne",
    ingredientname4: "Tomatoes",
    ingredientname5: "Marinara Sauce",
  },
  {
    Image:
      "https://res.cloudinary.com/freshly/image/upload/c_scale,w_640/c_crop,h_341,w_512/v1652893119/production-meal-image-6c9081ec-aecf-4eb0-980c-4843c3883727.jpg",
    Title: "Linguine Marinara & Beef Meatballs",
    Nutritions: "430 Cal | Has Gluten | Single-Serve",
    price: "$ 45",
    catagory: "Significant",
    mealcardsingle: "Single-Serve",
    mealcardmulti: "Multi-Serve",
    subrecipename: "with SautÃ©ed Zucchini & Spinach",
    meallabel1: "Gluten Free",
    meallabel2: "Soy Free",
    meallabel3: "Dairy Free",
    modalimg:
      "https://assets-global.website-files.com/5d03b4e13011831ae4624b37/61ff6b8bdf3b65256cd159c7_production-meal-image-0963d196-5110-4dc7-888a-8121e5b91142.jpeg",
    dishspecial1:
      "Pasta night gets an upgrade with gluten-free brown-rice pasta and our Masterful Marinara, packed with 5 sneaky veggies and a touch ofÂ honey",
    dishspecial2: "Nitrate- and nitrite-free pork sausage with ItalianÂ spices",
    ingredientname1: "Italian Sausage",
    ingredientname2: "Spinach",
    ingredientname2__1: "Zucchini",
    ingredientname3: "Penne",
    ingredientname4: "Tomatoes",
    ingredientname5: "Marinara Sauce",
  },
  {
    Image:
      "https://res.cloudinary.com/freshly/image/upload/c_scale,w_640/c_crop,h_341,w_512/v1656618770/production-meal-image-2076958f-3cde-4481-9644-0573e8ede33e.jpg",
    Title: "Wild-Caught Fish Cake",
    Nutritions: "570 Cal | Gluten Free | Single-Serve",
    price: "$ 46",
    catagory: "Significant",
    mealcardsingle: "Single-Serve",
    mealcardmulti: "Multi-Serve",
    subrecipename: "with SautÃ©ed Zucchini & Spinach",
    meallabel1: "Gluten Free",
    meallabel2: "Soy Free",
    meallabel3: "Dairy Free",
    modalimg:
      "https://assets-global.website-files.com/5d03b4e13011831ae4624b37/61ff6b8bdf3b65256cd159c7_production-meal-image-0963d196-5110-4dc7-888a-8121e5b91142.jpeg",
    dishspecial1:
      "Pasta night gets an upgrade with gluten-free brown-rice pasta and our Masterful Marinara, packed with 5 sneaky veggies and a touch ofÂ honey",
    dishspecial2: "Nitrate- and nitrite-free pork sausage with ItalianÂ spices",
    ingredientname1: "Italian Sausage",
    ingredientname2: "Spinach",
    ingredientname2__1: "Zucchini",
    ingredientname3: "Penne",
    ingredientname4: "Tomatoes",
    ingredientname5: "Marinara Sauce",
  },
  {
    Image:
      "https://res.cloudinary.com/freshly/image/upload/c_scale,w_640/c_crop,h_341,w_512/v1657287418/production-meal-image-788e2fb2-d7c2-4356-96ad-55559060765b.jpg",
    Title: "Salsa Roja Chicken Enchilada",
    Nutritions: "500 Cal | Gluten Free | Single-Serve",
    price: "$ 34",
    catagory: "Significant",
    mealcardsingle: "Single-Serve",
    mealcardmulti: "Multi-Serve",
    subrecipename: "with SautÃ©ed Zucchini & Spinach",
    meallabel1: "Gluten Free",
    meallabel2: "Soy Free",
    meallabel3: "Dairy Free",
    modalimg:
      "https://assets-global.website-files.com/5d03b4e13011831ae4624b37/61ff6b8bdf3b65256cd159c7_production-meal-image-0963d196-5110-4dc7-888a-8121e5b91142.jpeg",
    dishspecial1:
      "Pasta night gets an upgrade with gluten-free brown-rice pasta and our Masterful Marinara, packed with 5 sneaky veggies and a touch ofÂ honey",
    dishspecial2: "Nitrate- and nitrite-free pork sausage with ItalianÂ spices",
    ingredientname1: "Italian Sausage",
    ingredientname2: "Spinach",
    ingredientname2__1: "Zucchini",
    ingredientname3: "Penne",
    ingredientname4: "Tomatoes",
    ingredientname5: "Marinara Sauce",
  },
  {
    Image:
      "https://res.cloudinary.com/freshly/image/upload/c_scale,w_640/c_crop,h_341,w_512/v1655959139/production-meal-image-c2bd7c69-3db7-40c1-8740-e86f50357fcb.jpg",
    Title: "Indian-Spiced Red Lentil Dal",
    Nutritions: "620 Cal | Gluten Free | Single-Serve",
    price: "$ 15",
    catagory: "purelyplanet",
    mealcardsingle: "Single-Serve",
    mealcardmulti: "Multi-Serve",
    subrecipename: "with SautÃ©ed Zucchini & Spinach",
    meallabel1: "Gluten Free",
    meallabel2: "Soy Free",
    meallabel3: "Dairy Free",
    modalimg:
      "https://assets-global.website-files.com/5d03b4e13011831ae4624b37/61ff6b8bdf3b65256cd159c7_production-meal-image-0963d196-5110-4dc7-888a-8121e5b91142.jpeg",
    dishspecial1:
      "Pasta night gets an upgrade with gluten-free brown-rice pasta and our Masterful Marinara, packed with 5 sneaky veggies and a touch ofÂ honey",
    dishspecial2: "Nitrate- and nitrite-free pork sausage with ItalianÂ spices",
    ingredientname1: "Italian Sausage",
    ingredientname2: "Spinach",
    ingredientname2__1: "Zucchini",
    ingredientname3: "Penne",
    ingredientname4: "Tomatoes",
    ingredientname5: "Marinara Sauce",
  },
];

export default Menudata;
